[SDR_bt.1886]
profile-restore=copy
profile-desc=SDR
profile-cond=p["video-params/primaries"] == "bt.709" and get("video-params/gamma") == "bt.1886"
target-prim=bt.709
target-trc=bt.1886
target-peak=203

[SDR_gamma2.2]
profile-restore=copy
profile-desc=SDR
profile-cond=p["video-params/primaries"] == "bt.709" and get("video-params/gamma") == "gamma2.2"
target-prim=bt.709
target-trc=gamma2.2
target-peak=203

[SDR_gamma2.4]
profile-restore=copy
profile-desc=SDR
profile-cond=p["video-params/primaries"] == "bt.709" and get("video-params/gamma") == "gamma2.4"
target-prim=bt.709
target-trc=gamma2.4
target-peak=203
